//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public int Пол { get; set; }
        public int Роль { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        public virtual Пол Пол1 { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
