//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фильмы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фильмы()
        {
            this.Сеансы = new HashSet<Сеансы>();
        }
    
        public int id { get; set; }
        public string Название { get; set; }
        public System.DateTime Дата_выхода { get; set; }
        public int Возрастные_ограничения { get; set; }
        public int Жанр { get; set; }
    
        public virtual Жанры Жанры { get; set; }
        public virtual Ограничения Ограничения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сеансы> Сеансы { get; set; }
    }
}
